apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc-mysql
  namespace: assignment
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
